# Generated by Django 5.2.5 on 2026-08-07 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captures', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(80)], verbose_name='temperatura (°C)')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='umidade (%)')),
                ('measured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data/hora')),
                ('capture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_reading', to='captures.capture')),
            ],
            options={
                'verbose_name': 'leitura ambiental',
                'verbose_name_plural': 'leituras ambientais',
                'ordering': ('-measured_at',),
            },
        ),
    ]
