# Generated by Django 5.2.5 on 2026-08-07 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='captures/%Y/%m/', verbose_name='imagem')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data/hora')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('simulado', 'Simulado'), ('esp32', 'ESP32-CAM')], default='manual', max_length=10, verbose_name='origem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processada', 'Processada'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=12, verbose_name='status')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'captura',
                'verbose_name_plural': 'capturas',
                'ordering': ('-captured_at',),
            },
        ),
    ]
