# Generated by Django 5.2.5 on 2026-08-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captures', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fitossanitario', 'Fitossanitário'), ('baixa_confianca', 'Baixa confiança'), ('ambiental', 'Ambiental'), ('critico', 'Crítico')], db_index=True, max_length=20, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, max_length=8, verbose_name='severidade')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data/hora')),
                ('viewed', models.BooleanField(db_index=True, default=False, verbose_name='visualizado')),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='captures.capture')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ('-created_at',),
            },
        ),
    ]
