# Generated by Django 5.2.5 on 2026-08-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='predictions.prediction'),
        ),
    ]
